pipeline test

diff --git a/.github/workflows/integrate.yml b/.github/workflows/integrate.yml
--- a/.github/workflows/integrate.yml
+++ b/.github/workflows/integrate.yml
@@ -32,6 +32,15 @@ jobs:
       - name: Build application with docker compose
         run: docker-compose -f docker-compose-production.yml up -d
 
+      - name: Start Docker Compose and check logs
+        run: |
+          docker-compose -f docker-compose-production.yml up -d
+          sleep 5  # Give some time for containers to initialize
+          docker-compose logs
+
+      - name: Check backend container logs
+        run: docker logs backend || true  # Use || true to ensure this command does not fail the workflow
+
       - name: Check available system memory
         run: free -m
       
